[project]
name = "opticol"
version = "1.0.1"
description = "Memory optimized implementations for the main Python Collection ABCs."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.black]
line-length = 100
target-version = ["py312"]
preview = true

[tool.uv.sources]
guppy3 = { git = "https://github.com/zhuyifei1999/guppy3.git", rev = "da86ab98abf20c57b9ead4d653157af8baaa8efd" }

[tool.pylint.design]
max-args=7
min-public-methods=1

[tool.pylint.similarities]
min-similarity-lines=0

[tool.pytest]
testpaths = ["tests"]
python_files = ["test_*.py", "bench_*.py"]
python_functions = ["test_", "bench_"]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "codespell>=2.4.2",
    "guppy3",
    "mypy>=2.1.0",
    "pylint>=4.0.4",
    "pytest>=9.0.3",
    "pytest-benchmark>=5.2.3",
    "pytest-regex>=0.2.0",
]
